name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          autoconf
          automake-wrapper
          make
          libtool
    - uses: actions/checkout@v3
    - run: ./setup.sh
    - run: ./build.sh
    - run: ./test.sh
    - uses: actions/upload-artifact@v3
    - uses: actions/download-artifact@v3
